main: org.kayteam.simplehomes.SimpleHomes
name: SimpleHomes
version: '${project.version}'
author: SirOswaldo
website: https://www.kayteam.org
api-version: 1.13
softdepend: [ PlaceholderAPI, Vault ]
commands:
  SetHome:
    description: Set a home
  DeleteHome:
    description: Delete a home
  Home:
    description: Teleport to home
  Homes:
    description: Open inventory
  SimpleHomes:
    description: Manage this plugin
  MigrateHomes:
    description: Migrate homes from others plugins.
  PermissionCommand:
    description: Prueba
permissions:
  simple.admin.homes:
    description: Manage this plugin
  simple.set.home:
    description: Set a home
  simple.delete.home:
    description: Delete a home
  simple.home:
    description: Teleport to home
  simple.homes:
    description: Open homes inventory
  simple.homes.other:
    description: Open other homes inventory
  simple.bypass.home.countdown:
    description: Bypass countdown teleport
  simple.bypass.home.movement:
    description: Bypass movement teleport
  simple.bypass.home.cost:
    description: Bypass home cost
  simple.bypass.home.disabled.worlds:
    description: Bypass disabled worlds
  simple.notify.update:
    description: Notify to plugin update
  simple.migrate.homes:
    description: Migrate homes from others plugins