main: club.spfmc.simplehomes.SimpleHomes
name: SimpleHomes
version: 1.2
author: SirOswaldo
website: "https://www.kayteam.org"
softdepend:
  - PlaceholderAPI
commands:
  SetHome:
    description: Set a home
  DeleteHome:
    description: Delete a home
  Home:
    description: Teleport to home
  Homes:
    description: Open inventory
  SimpleHomes:
    description: Manage this plugin
permissions:
  simple.admin.homes:
    description: Manage this plugin
  simple.set.home:
    description: Set a home
  simple.delete.home:
    description: Delete a home
  simple.home:
    description: Teleport to home
  simple.homes:
    description: Open homes inventory
  simple.homes.other:
    description: Open other homes inventory
  simple.bypass.home.countdown:
    description: Bypass countdown teleport
  simple.bypass.home.movement:
    description: Bypass movement teleport