teleport:
  countdown: 10
  messages:
    10: "&e&lSimple&6&lHomes &8» &fTeleporting in &9%seconds%&f..."
    0: "&e&lSimple&6&lHomes &8» &fYou have been teleported to home: &9%home_name%&f."
  sounds:
    10: "NOTE_PLING"
    9: "NOTE_PLING"
    8: "NOTE_PLING"
    7: "NOTE_PLING"
    6: "NOTE_PLING"
    5: "NOTE_PLING"
    4: "NOTE_PLING"
    3: "NOTE_PLING"
    2: "NOTE_PLING"
    1: "NOTE_PLING"
    0: "ENDERMAN_TELEPORT"
  titles:
    10:
      title: "&6Teleporting in &9%seconds%&f..."
      subTitle: "&fDestiny: &9%home_name%"
    0:
      title: "&6Teletansported completed"
      subTitle: "&fHome: &9%home_name%"
vault:
  enable: false
  setHome: 100.0 # Set Home Cost
  overwriteHome: 50.0 # Overwrite Home Cost
  deleteHome: 100.0 # Refund Amount For Delete Home
  teleport: 100.0 # Cost of teleport to your home
world:
  # Disable the set home in specific worlds
  disableSetHome:
    enable: false
    worlds:
      - "world_nether"
      - "world_the_end"
  # Disable start teleport in current location world
  disableTeleportFrom:
    enable: false
    worlds:
      - "world_nether"
      - "world_the_end"
  # Disable the arrival of a teleportation on specific worlds
  disableTeleportTo:
    enable: false
    worlds:
      - "world_nether"
      - "world_the_end"
homes:
  default: 2
  vip: 5 # simple.max.homes.vip
  staff: 10 # simple.max.homes.staff
inventory:
  deleteConfirm:
    title: "&8▪ &c&lDelete your home?"
    rows: 3
    items:
      gray-panel:
        material: "GRAY_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "0-1"
          - "9"
      orange-panel:
        material: "ORANGE_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "17"
          - "25-26"
      home-information:
        material: "RED_BED"
        name: "%home-display-name%"
        slots:
          - "13"
        lore:
          - "&6"
          - '&6&l┏&c&lCords'
          - '&6&l┣►&fWORLD &7► &e%home-world-name%'
          - '&6&l┣►&fX &7► &e%home-world-x%'
          - '&6&l┣►&fY &7► &e%home-world-y%'
          - '&6&l┣►&fZ &7► &e%home-world-z%'
          - '&6&l┣►&fYAW &7► &e%home-world-yaw%'
          - '&6&l┣►&fPITCH &7► &e%home-world-pitch%'
          - '&6'
          - '&6&l┏&c&lInfo'
          - '&6&l┣►&fType &7► &cPRIVATE &aPUBLIC'
          - '&6&l┣►&fCost &7► &e$120.0'
      accept-button:
        material: "LIME_WOOL"
        name: "&8▪ &a&lAccept &8▪"
        lore:
          - "&6"
          - "&8▪ &aClick to delete!"
        slots:
          - "11"
        left-click-actions:
          - "[accept]"
      cancel-button:
        material: "RED_WOOL"
        name: "&8▪ &c&lCancel &8▪"
        lore:
          - "&6"
          - "&8▪ &aClick to save!"
        slots:
          - "15"
        left-click-actions:
          - "[cancel]"
  homes:
    rows: 4
    title: "Homes Inventory"
    items:
      panel:
        material: "ORANGE_STAINED_GLASS_PANE"
        name: "&7"
      information:
        material: "PAPER"
        name: "&6Information"
        lore:
          - "&7"
          - "&6Owner: %owner%"
          - "&6Amount: %amount%"
      home:
        material: "CHEST"
        name: "%display-name%"
        lore:
          - '&6&l┏&c&lCords'
          - '&6&l┣&fWORLD &7► &e%home-world-name%'
          - '&6&l┣&fX &7► &e%home-world-x%'
          - '&6&l┣&fY &7► &e%home-world-y%'
          - '&6&l┣&fZ &7► &e%home-world-z%'
          - '&6&l┣&fZ &7► &e%home-world-yaw%'
          - '&6&l┣&fZ &7► &e%home-world-pitch%'
          - '&6'
          - '&6&l┏&c&lPublic'
          - '&6&l┣&fPublic &7► &e%home-public%'
          - '&6&l┣&fCost &7► &e%home-public-cost%'
          - '&6'
          - '&5Left Click to teleport'
          - '&6Middle Click to edit'
          - '&cRight Click to delete'
      prevPage:
        material: "ARROW"
        name: "&cPrev Page"
      nextPage:
        material: "ARROW"
        name: "&cNext Page"
      close:
        material: "BARRIER"
        name: "&cClose Menu"
  admin:
    title: "&8▪ &c&lPlugin management"
    rows: 5
    items:
      gray-panel:
        material: "GRAY_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "0-1"
          - "9"
      orange-panel:
        material: "ORANGE_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "35-36"
          - "43-44"
      world-settings-menu:
        material: PAPER
        name: "&8▪ &c&lWorld settings menu &8▪"
        lore:
          - "&6"
          - "&8▪ &aLeft click to open menu!"
        slots:
          - "20"
        left-click-actions:
          - "[world-settings]"
      vault-settings-menu:
        material: PAPER
        name: "&8▪ &c&lVault settings menu &8▪"
        lore:
          - "&6"
          - "&8▪ &aLeft click to open menu!"
        slots:
          - "22"
        left-click-actions:
          - "[vault-settings]"
      reload:
        material: REDSTONE_BLOCK
        name: "&8▪ &c&lReload plugin &8"
        lore:
          - ""
          - "&8▪ &aLeft click to reload!"
        slots:
          - "24"
        left-click-actions:
          - "[reload]"
      close-button:
        material: "BARRIER"
        name: "&8▪ &c&lClose &8▪"
        lore:
          - "&6"
          - "&8▪ &aLeft click to close!"
        slots:
          - "8"
        left-click-actions:
          - "[close]"
  vault:
    title: "&8▪ &c&lVault settings menu"
    rows: 5
    update-inverval: 2
    texts:
      enabled: "&a&lEnabled"
      disabled: "&c&lDisabled"
    items:
      gray-panel:
        material: "GRAY_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "0-1"
          - "9"
      orange-panel:
        material: "ORANGE_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "35"
          - "43-44"
      vault-status:
        update: true
        material: CHEST
        name: "&8▪ &c&lVault status &8▪"
        lore:
          - ""
          - "&6Status&e: %vault-status%"
          - ""
          - "&8▪ &aLeft click to toggle!"
        slots:
          - "11"
        left-click-actions:
          - "[toggle-vault-status]"
      set-home-cost:
        material: PAPER
        name: "&8▪ &c&lSet home cost &8▪"
        lore:
          - ""
          - "&6Cost&e: %set-home-cost%"
          - ""
          - "&8▪ &aLeft click to change!"
        slots:
          - "30"
        left-click-actions:
          - "[change-set-home-cost]"
      overwrite-cost:
        material: PAPER
        name: "&8▪ &c&lOverwrite home cost &8▪"
        lore:
          - ""
          - "&6Cost&e: %overwrite-home-cost%"
          - ""
          - "&8▪ &aLeft click to change!"
        slots:
          - "31"
        left-click-actions:
          - "[change-overwrite-home-cost]"
      delete-home-refund:
        material: PAPER
        name: "&8▪ &c&lDelete home refund &8▪"
        lore:
          - ""
          - "&6Amount&e: %delete-home-cost%"
          - ""
          - "&8▪ &aLeft click to change!"
        slots:
          - "32"
        left-click-actions:
          - "[change-delete-home-cost]"
      teleport-cost:
        material: PAPER
        name: "&8▪ &c&lTeleport cost &8▪"
        lore:
          - ""
          - "&6Money&e: %teleport-home-cost%"
          - ""
          - "&8▪ &aLeft click to change!"
        slots:
          - "33"
        left-click-actions:
          - "[change-teleport-home-cost]"
      return-button:
        material: "ARROW"
        name: "&8▪ &c&lReturn &8▪"
        lore:
          - "&6"
          - "&8▪ &aLeft click to return!"
        slots:
          - "36"
        left-click-actions:
          - "[return]"
      close-button:
        material: "BARRIER"
        name: "&8▪ &c&lClose &8▪"
        lore:
          - "&6"
          - "&8▪ &aLeft click to close!"
        slots:
          - "8"
        left-click-actions:
          - "[close]"
  world:
    title: "&8▪ &c&lDisabled world menu"
    rows: 5
    update-interval: 2
    texts:
      enabled: "&a&lEnabled"
      disabled: "&c&lEnabled"
    items:
      gray-panel:
        material: "GRAY_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "0-1"
          - "9"
      orange-panel:
        material: "ORANGE_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "35"
          - "43-44"

      set-home-settings:
        update: true
        material: CHEST
        name: "&8▪ &c&lSet home settings &8▪"
        lore:
          - ""
          - "&6&lStatus &7► %set-home-status%"
          - ""
          - "&8▪ &aLeft click to toggle"
          - "&8▪ &aRight click to manage worlds"
        slots:
          - "20"
        left-click-actions:
          - "[toggle-set-home]"
        right-click-actions:
          - "[manage-set-home-worlds]"
      teleportFrom:
        update: true
        material: CHEST
        name: "&8▪ &c&lTeleport from settings &8▪"
        lore:
          - ""
          - "&6&lStatus &7► %teleport-from-status%"
          - ""
          - "&8▪ &aLeft click to toggle"
          - "&8▪ &aRight click to manage worlds"
        slots:
          - "22"
        left-click-actions:
          - "[toggle-teleport-from]"
        right-click-actions:
          - "[manage-teleport-from-worlds]"
      teleportTo:
        material: CHEST
        name: "&8▪ &c&lTeleport to settings &8▪"
        lore:
          - ""
          - "&6&lStatus &7► %teleport-to-status%"
          - ""
          - "&8▪ &aLeft click to toggle"
          - "&8▪ &aRight click to manage worlds"
        slots:
          - "24"
        left-click-actions:
          - "[toggle-teleport-to]"
        right-click-actions:
          - "[manage-teleport-to-worlds]"

      return-button:
        material: "ARROW"
        name: "&8▪ &c&lReturn &8▪"
        lore:
          - "&6"
          - "&8▪ &aLeft click to return!"
        slots:
          - "36"
        left-click-actions:
          - "[return]"
      close-button:
        material: "BARRIER"
        name: "&8▪ &c&lClose &8▪"
        lore:
          - "&6"
          - "&8▪ &aLeft click to close!"
        slots:
          - "8"
        left-click-actions:
          - "[close]"

  worldSetHome:
    title: "Disabled Set Home Worlds"
    rows: 1
    status:
      enable: "&aEnabled"
      disable: "&cDisabled"
    items:
      item:
        material: PAPER
        name: "%world_name%"
        lore:
          - ""
          - "&6Status&e: %status%"
      panel:
        material: "ORANGE_STAINED_GLASS_PANE"
      information:
        material: CHEST
        name: "&3Information"
        lore:
          - ""
          - "&fIf the world is activated,"
          - "&fit means that homes cannot"
          - "&fbe established in it."
      next:
        material: ARROW
        name: "&aNext Page"
      previous:
        material: ARROW
        name: "&aPrevious Page"
      close:
        material: BARRIER
        name: "&cClose"
  worldTeleportFrom:
    title: "Disabled Teleport From Worlds"
    rows: 1
    status:
      enable: "&aEnabled"
      disable: "&cDisabled"
    items:
      item:
        material: PAPER
        name: "%world_name%"
        lore:
          - ""
          - "&6Status&e: %status%"
      panel:
        material: "ORANGE_STAINED_GLASS_PANE"
      information:
        material: CHEST
        name: "&3Information"
        lore:
          - ""
          - "&fIf the world is activated,"
          - "&fit means that a teleportation"
          - "&fcannot be started"
          - "&fby teleportation from home."
      next:
        material: ARROW
        name: "&aNext Page"
      previous:
        material: ARROW
        name: "&aPrevious Page"
      close:
        material: BARRIER
        name: "&cClose"
  worldTeleportTo:
    title: "Disabled Teleport To Worlds"
    rows: 1
    status:
      enable: "&aEnabled"
      disable: "&cDisabled"
    items:
      item:
        material: PAPER
        name: "%world_name%"
        lore:
          - ""
          - "&6Status&e: %status%"
      panel:
        material: "ORANGE_STAINED_GLASS_PANE"
      information:
        material: CHEST
        name: "&3Information"
        lore:
          - ""
          - "&fIf the world is activated,"
          - "&fit means that it cannot be reached"
          - "&fby teleportation from home."
      next:
        material: ARROW
        name: "&aNext Page"
      previous:
        material: ARROW
        name: "&aPrevious Page"
      close:
        material: BARRIER
        name: "&cClose"


  homeEditor:
    title: "&8▪ &c&lHome editor"
    rows: 5
    update-inverval: 2
    texts:
      public: "&a&lPublic"
      private: "&c&lPrivate"
    items:
      gray-panel:
        material: "GRAY_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "0-1"
          - "9"
      orange-panel:
        material: "ORANGE_STAINED_GLASS_PANE"
        name: "&6&lSimple&f&lHomes"
        slots:
          - "35"
          - "43-44"
      home-information:
        material: "CHEST"
        name: "%home-display-name%"
        lore:
          - "&6"
          - '&6&l┏&c&lCords'
          - '&6&l┣►&fWORLD &7► &e%home-world-name%'
          - '&6&l┣►&fX &7► &e%home-world-x%'
          - '&6&l┣►&fY &7► &e%home-world-y%'
          - '&6&l┣►&fZ &7► &e%home-world-z%'
          - '&6&l┣►&fYAW &7► &e%home-world-yaw%'
          - '&6&l┣►&fPITCH &7► &e%home-world-pitch%'
          - '&6'
          - '&6&l┏&c&lInfo'
          - '&6&l┣►&fType &7► &cPRIVATE &aPUBLIC'
          - '&6&l┣►&fCost &7► &e$120.0'

      public-status:
        material: "PAPER"
        name: "&8▪ &c&lHome public &8▪"
        lore:
          - ""
          - "&6&lStatus &7► %set-home-status%"
          - ""
          - "&8▪ &aLeft click to toggle"
        slots:
          - "30"
      public-teleport-cost: ""
      private-players-permited: ""

      return-button:
        material: "ARROW"
        name: "&8▪ &c&lReturn &8▪"
        lore:
          - ""
          - "&8▪ &aLeft click to return!"
        slots:
          - "36"
        left-click-actions:
          - "[return]"
      close-button:
        material: "BARRIER"
        name: "&8▪ &c&lClose &8▪"
        lore:
          - ""
          - "&8▪ &aLeft click to close!"
        slots:
          - "8"
        # left-click-actions
        # left-shift-click-actions
        # middle-click-actions
        # right-click-actions
        # right-shift-click-actions
        # click-actions
        left-click-actions:
          - "[close]"