teleport:
  countdown: 10
  messages:
    10: "&e&lSimple&6&lHomes &8» &fTeleporting in &9%seconds%&f..."
    0: "&e&lSimple&6&lHomes &8» &fYou have been teleported to home: &9%home_name%&f."
  sounds:
    10: "NOTE_PLING"
    9: "NOTE_PLING"
    8: "NOTE_PLING"
    7: "NOTE_PLING"
    6: "NOTE_PLING"
    5: "NOTE_PLING"
    4: "NOTE_PLING"
    3: "NOTE_PLING"
    2: "NOTE_PLING"
    1: "NOTE_PLING"
    0: "ENDERMAN_TELEPORT"
  titles:
    10:
      title: "&6Teleporting in &9%seconds%&f..."
      subTitle: "&fDestiny: &9%home_name%"
    0:
      title: "&6Teletansported completed"
      subTitle: "&fHome: &9%home_name%"
vault:
  setHome: 100.0 # Set Home Cost
  overwriteHome: 50.0 # Overwrite Home Cost
  deleteHome: 100.0 # Refund Amount For Delete Home
homes:
  default: 2
  vip: 5 # simple.max.homes.vip
  staff: 10 # simple.max.homes.staff
inventory:
  deleteConfirm:
    title: "Do you want to erase your home?"
    items:
      panel:
        material: "STAINED_GLASS_PANE"
        data: 1
        name: "&7"
      information:
        material: "BED"
        name: "&6%name%"
        lore:
          - "&7"
          - "&6WORLD &e%world%"
          - "&6X &e%x%"
          - "&6Y &e%y%"
          - "&6Z &e%z%"
          - "&6YAW  &e%yaw%"
          - "&6PITCH &e%pitch%"
          - "&7"
      accept:
        material: "WOOL"
        data: 5
        name: "&aAccept"
      cancel:
        material: "WOOL"
        data: 14
        name: "&cCancel"
  homes:
    rows: 3
    title: "Homes Inventory"
    items:
      panel:
        material: "STAINED_GLASS_PANE"
        data: 1
        name: "&7"
      information:
        material: "PAPER"
        name: "&6Information"
        lore:
          - "&7"
          - "&6Owner: %owner%"
          - "&6Amount: %amount%"
      home:
        material: "CHEST"
        name: "&e%name%"
        lore:
          - "&7"
          - "&6WORLD &e%world%"
          - "&6X &e%x%"
          - "&6Y &e%y%"
          - "&6Z &e%z%"
          - "&6YAW  &e%yaw%"
          - "&6PITCH &e%pitch%"
          - "&7"
          - "&6Left Click &eTeleport to home"
          - "&6Right Click &eDelete the home"
      prevPage:
        material: "ARROW"
        name: "&cPrev Page"
      nextPage:
        material: "ARROW"
        name: "&cNext Page"
      close:
        material: "BARRIER"
        name: "&cClose Menu"